(function(root){
'use strict';
const aliases={айфон:'iphone',айфоны:'iphone',макбук:'macbook',мак:'mac',айпад:'ipad',эйрподс:'airpods',аирподс:'airpods',аирподсы:'airpods',эпл:'apple',вотч:'watch',часы:'watch',наушники:'airpods',ноутбук:'macbook',планшет:'ipad',телефон:'iphone',эйр:'air',про:'pro',гб:'gb',тб:'tb'};
function normalize(s){return String(s||'').toLowerCase().replace(/ё/g,'е').replace(/([0-9])([a-zа-я])/g,'$1 $2').replace(/([a-zа-я])([0-9])/g,'$1 $2').replace(/[^a-zа-я0-9]+/g,' ').trim().split(/\s+/).map(w=>aliases[w]||w).join(' ')}
function options(p){return {memory:p.memory.length?p.memory:[''],color:p.colors,sim:p.category==='iPhone'?['Dual eSIM']:p.category==='iPad'?['Wi-Fi']:[''],ram:p.category==='Mac'?['16 ГБ','24 ГБ','32 ГБ']:['']}}
function selection(p,s={}){const o=options(p),v={};for(const k of Object.keys(o))v[k]=o[k].includes(s[k])?s[k]:o[k][0];return v}
function variant(p,s={}){const v=selection(p,s),o=options(p),key=[p.id,...Object.values(v)].join('|');return {key,id:p.id,...v,price:(v.memory===o.memory[0]&&v.ram===o.ram[0])?p.price:null,image:p.colorImages?.[o.color.indexOf(v.color)]||p.image,status:'quote'}}
function variants(p){const o=options(p),a=[];for(const memory of o.memory)for(const color of o.color)for(const sim of o.sim)for(const ram of o.ram)a.push(variant(p,{memory,color,sim,ram}));return a}
function matches(p,q){const words=normalize(q).split(' ').filter(Boolean),text=normalize([p.name,p.category,...p.memory,...p.colors,...(p.highlights||[]),...Object.values(p.specs||{}),...options(p).sim,...options(p).ram].join(' '));return words.every(w=>text.includes(w))}
function filter(list,f={},favorites=[]){let result=list.filter(p=>(!f.category||f.category==='Все'||p.category===f.category)&&(f.scope!=='favorites'||favorites.includes(p.id))&&matches(p,f.q)&&(!f.memory||p.memory.includes(f.memory))&&(!f.sim||options(p).sim.includes(f.sim))&&(!f.ram||options(p).ram.includes(f.ram))&&(!f.color||p.colors.includes(f.color))&&(!f.stock||f.stock==='quote')&&(!f.min||p.price>=Number(f.min))&&(!f.max||p.price<=Number(f.max)));if(f.sort==='asc')result.sort((a,b)=>a.price-b.price);if(f.sort==='desc')result.sort((a,b)=>b.price-a.price);if(f.sort==='name')result.sort((a,b)=>a.name.localeCompare(b.name,'ru'));return result}
function cleanCart(input,list){const rows=[];if(!Array.isArray(input))return rows;for(const x of input){if(!x||typeof x!=='object')continue;const p=list.find(p=>p.id===x.id);if(!p||!Number.isInteger(x.qty)||x.qty<1)continue;const v=variant(p,x);const row=rows.find(r=>r.key===v.key);if(row)row.qty=Math.min(99,row.qty+x.qty);else rows.push({...v,qty:Math.min(99,x.qty)})}return rows}
function totals(cart){return {qty:cart.reduce((s,x)=>s+x.qty,0),amount:cart.reduce((s,x)=>s+(x.price||0)*x.qty,0),unpriced:cart.filter(x=>x.price===null).reduce((s,x)=>s+x.qty,0)}}
function change(cart,v,delta){const next=cart.map(x=>({...x})),i=next.findIndex(x=>x.key===v.key);if(i<0&&delta>0)next.push({...v,qty:Math.min(99,delta)});else if(i>=0)next[i].qty=Math.min(99,next[i].qty+delta);return next.filter(x=>x.qty>0)}
function customerErrors(data){const errors={};if((data.name||'').trim().length<2)errors.name='Укажите ваше имя';const digits=(data.phone||'').replace(/\D/g,'');if(digits.length<10||digits.length>15)errors.phone='Проверьте номер: от 10 до 15 цифр';if(!(data.city||'').trim())errors.city='Укажите город';if(data.delivery==='courier'&&!(data.address||'').trim())errors.address='Укажите адрес доставки';return errors}
root.ShopCore={normalize,options,selection,variant,variants,matches,filter,cleanCart,totals,change,customerErrors};
})(globalThis);
