const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'..'),ctx=vm.createContext({URLSearchParams,console});
for(const name of ['store-config.js','products.js','solar.js','core.js','app.js'])vm.runInContext(fs.readFileSync(path.join(base,name),'utf8'),ctx,{filename:name});
const C=ctx.ShopCore,products=vm.runInContext('products',ctx);let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name)}
test('Russian aliases, case, compact units and combined queries',()=>{assert.equal(C.filter(products,{q:'АЙФОН 256ГБ'}).length,2);assert.equal(C.filter(products,{q:'макбук 16 гб'}).length,1);assert.equal(C.filter(products,{q:'наушники'}).length,1);assert.equal(C.filter(products,{q:'айпад 128'}).length,1);assert.equal(C.filter(products,{q:'айфон18 про'}).length,1);assert.equal(C.filter(products,{q:'неизвестная модель'}).length,0)});
test('Category, memory, budget and favorites combine',()=>{const f={category:'iPhone',memory:'256 ГБ',max:150000,scope:'favorites'};assert.equal(C.filter(products,f,['iphone-18-pro']).length,1);assert.equal(C.filter(products,f,['iphone-duo']).length,0);assert.equal(C.filter(products,{category:'Mac',sim:'Dual eSIM'}).length,0)});
test('Price sort and no mutation of catalog order',()=>{const ids=products.map(p=>p.id).join();const sorted=C.filter(products,{sort:'asc'});assert.equal(sorted[0].id,'airpods-pro');assert.equal(products.map(p=>p.id).join(),ids)});
test('Variant keys separate memory and color, photos match color',()=>{const p=products[1],a=C.variant(p),b=C.variant(p,{color:'Black'}),c=C.variant(p,{memory:'512 ГБ'});assert.notEqual(a.key,b.key);assert.notEqual(a.key,c.key);assert.equal(b.image,'iphone-18-pro-black-full.png');assert.equal(a.price,129990);assert.equal(c.price,null)});
test('All variants have unique keys and existing image assets',()=>{for(const p of products){const list=C.variants(p);assert.equal(new Set(list.map(v=>v.key)).size,list.length);for(const v of list)assert(fs.existsSync(path.join(base,'assets',v.image)))}});
test('Unconfirmed RAM pricing remains unknown',()=>{assert.equal(C.variant(products[2],{ram:'32 ГБ'}).price,null);assert.equal(C.variant(products[2],{ram:'16 ГБ'}).price,109990)});
test('Cart is immutable, separate variants, quantity limits and removal',()=>{const a=C.variant(products[1]),b=C.variant(products[1],{color:'Black'});const first=C.change([],a,1),next=C.change(first,b,1);assert.equal(first.length,1);assert.equal(next.length,2);assert.equal(C.change(next,a,200)[0].qty,99);assert.equal(C.change(next,a,-1).length,1)});
test('Cart rehydrates using catalog prices, ignoring tampered prices',()=>{const v=C.variant(products[1]);const clean=C.cleanCart([{...v,price:1,qty:2},{id:'missing',qty:3},{...v,qty:-1},{...v,qty:1.5}],products);assert.equal(clean.length,1);assert.equal(clean[0].price,129990);assert.equal(clean[0].qty,2);assert.equal(C.cleanCart(null,products).length,0)});
test('Unknown amounts are not presented as a complete total',()=>{const a=C.variant(products[0]),b=C.variant(products[1],{memory:'512 ГБ'}),t=C.totals([{...a,qty:1},{...b,qty:2}]);assert.equal(t.amount,199990);assert.equal(t.qty,3);assert.equal(t.unpriced,2)});
test('Checkout validates name, phone, city and courier address',()=>{assert.equal(Object.keys(C.customerErrors({})).length,3);assert.equal(Object.keys(C.customerErrors({name:'Иван',phone:'+7 999 123-45-67',city:'Москва',delivery:'pickup'})).length,0);assert(C.customerErrors({name:'Иван',phone:'+7 999 123-45-67',city:'Москва',delivery:'courier'}).address);assert(C.customerErrors({name:'Иван',phone:'123',city:'Москва'}).phone)});
test('Every public route prerenders without DOM',()=>{for(const r of ['home','catalog','cart','checkout','contacts','about','delivery','warranty','support','guides','compare']){const html=ctx.ShopUI.render(r,'');assert(html.length>50);assert(!html.includes('undefined'))}for(const p of products){const html=ctx.ShopUI.render('product','id='+p.id);assert(html.includes(p.name));assert(html.includes('Наличие уточняется'))}});
test('Untrusted query and variant values are escaped in HTML',()=>{const html=ctx.ShopUI.render('catalog','q='+encodeURIComponent('<script>alert(1)</script>'));assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'))});
test('Preview order mode cannot claim submitted orders',()=>{assert.equal(ctx.SHOP_CONFIG.demo,true);assert.equal(ctx.SHOP_CONFIG.orderEndpoint,'');const html=ctx.ShopUI.render('cart','');assert(!html.includes('Заказ принят'))});
console.log(passed+' checks passed');
