const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.resolve(__dirname,'..');
const context=vm.createContext({URLSearchParams,console});
for(const name of ['store-config.js','products.js','solar.js','core.js','app.js'])vm.runInContext(fs.readFileSync(path.join(base,name),'utf8'),context,{filename:name});
const products=vm.runInContext('products',context),config=context.SHOP_CONFIG;
const pages=[['index','home','iShop — устройства для вашего дня','Коллекция iShop: устройства Apple, выбор комплектации и сравнение моделей.'],['catalog','catalog','Каталог устройств — iShop','Подберите устройство по модели, памяти, SIM и бюджету. Сохраняйте и сравнивайте свой выбор.'],['cart','cart','Корзина — iShop','Ваша подборка устройств iShop: комплектации, количество и ориентировочная стоимость.'],['checkout','checkout','Оформление — iShop','Контактные данные, получение и проверка выбранной комплектации.'],['contacts','contacts','Контакты — iShop','Способы связи с магазином iShop.'],['about','about','О магазине — iShop','Знакомство с iShop и коллекцией устройств.'],['delivery','delivery','Доставка и оплата — iShop','Информация о получении и оплате выбранного устройства.'],['warranty','warranty','Гарантия и возврат — iShop','Уточните условия гарантийного обслуживания выбранного товара.'],['support','support','Помощь — iShop','Ответы на вопросы об ассортименте, корзине и подборе устройств.'],['guides','guides','Помощь с выбором — iShop','Разбираемся в памяти, SIM и параметрах Mac.'],['compare','compare','Сравнение устройств — iShop','Сравните характеристики до трёх устройств.'],['favorites','catalog','Избранное — iShop','Ваши сохранённые устройства.']];
for(const p of products)pages.push(['product-'+p.id,'product',p.name+' — iShop',p.name+': фотографии, комплектация, выбор памяти и цвета.','id='+p.id]);
pages.push(['product','product','Устройство — iShop','Подберите комплектацию устройства iShop.','id='+products[0].id]);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const [file,route,title,description,query]of pages){const q=query||(file==='favorites'?'scope=favorites':'');const main=context.ShopUI.render(route,q);const canonical=config.siteUrl?`<link rel="canonical" href="${escape(new URL(file+'.html',config.siteUrl.endsWith('/')?config.siteUrl:config.siteUrl+'/').href)}">`:'';const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#100508"><meta name="description" content="${escape(description)}"><meta name="robots" content="${config.demo?'noindex,nofollow':'index,follow'}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="website"><title>${escape(title)}</title>${canonical}<link rel="icon" type="image/svg+xml" href="favicon.svg"><link rel="stylesheet" href="style.css?v=2"><script src="theme.js"></script><script defer src="store-config.js"></script><script defer src="products.js"></script><script defer src="solar.js"></script><script defer src="core.js"></script><script defer src="app.js?v=2"></script><script defer src="effects.js?v=2"></script></head><body data-page="${route}">${context.ShopUI.header()}<main id="main" class="wrap">${main}</main>${context.ShopUI.footer()}${context.ShopUI.dock()}${context.ShopUI.dialogs()}<noscript><div class="wrap notice">Каталог доступен для просмотра. Для фильтров, избранного и корзины включите JavaScript.</div></noscript></body></html>`;fs.writeFileSync(path.join(base,file+'.html'),html)}
fs.writeFileSync(path.join(base,'robots.txt'),config.demo?'User-agent: *\nDisallow: /\n':'User-agent: *\nAllow: /\n'+(config.siteUrl?'Sitemap: '+new URL('sitemap.xml',config.siteUrl.endsWith('/')?config.siteUrl:config.siteUrl+'/').href+'\n':''));
if(config.siteUrl&&!config.demo){fs.writeFileSync(path.join(base,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.filter(p=>!['cart','checkout','favorites','compare','product'].includes(p[0])).map(p=>'<url><loc>'+escape(new URL(p[0]+'.html',config.siteUrl.endsWith('/')?config.siteUrl:config.siteUrl+'/').href)+'</loc></url>').join('')+'</urlset>')}
console.log('Built '+pages.length+' prerendered pages. Mode: '+(config.demo?'preview':'store'));
